---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments
baseurl: /SALMA


### content configuration ###
title:       "Salma - Make it best from Word and Team Foundation Server!"
keywords:    "SALMA, MS TFS, Team Foundation Server, TFS, Word, requirements, download, Word2TFS, TFS2Word, manage requirements, open source"
description: "Open source product which allows efficiently manage requirements in Word and TFS."
source_link: "https://github.com/SoftServeInc/SALMA"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  gray:		 '#B0B0B0'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  
